export const PROJECT_ALPHA = [
  'empl-web-api',
  'cust-web-api',
  'renew-web-api',
  'messages-api',
  'cms-api',
  'customer-api',
  'ecm-api',
  'etl-api',
  'email-service',
  'loan-api',
  'bulk-messages-api',
  'espn-api',
  'request-api',
  'rules-api',
  'security-api',
  'sms-api',
  'documents-api',
  'authentication-api',
];

export const PROJECT_BETA = [
  'income-web-api',
  'audit-service',
  'espn-backend-app',
  'broker-service',
  'employee-service-api',
  'kyc-service',
  'notification-service',
  'credit-service',
  'experience-credit-service',
  'experience-process-service',
  'experience-system-service',
  'system-credit-customer',
  'system-credit-employee',
  'espn-poc-services',
];
